### ISSUE TITLE
Selective sync is not working!

### ISSUE THREAD

**Issue by dataprolet** [juanitomint/nextcloud-client-docker#15]
I tried this container using the _unsyncfolders_ and _exclude_ settings as well as the _NC_PATH_ environment variable, but the Nextcloud client is still syncing all folders. I know this container is probably unmaintained, but I still wanted to point that out.

Server is Nextcloud v25.0.3.2.

**Comment by juanitomint** [comment]
Hey there yup pretty much unmaintained but if I have some time to spare I'll try to patch it cause some ppl is using it
If you have a solution please do a PR so we keep it up to date

**Comment by dataprolet** [comment]
Thanks but I created my own Docker container in the meantime. Also I think it might also be an issue with nextcloudcmd, at least there are several open issues regarding the _unsyncfolders_ and _exclude_ flags as well as stalling sync: https://github.com/nextcloud/desktop/issues/3144
