### ISSUE TITLE
No files are uploaded

### ISSUE THREAD

**Issue by mgutt** [juanitomint/nextcloud-client-docker#2]
I tested the container through Unraid. After choosing my settings Unraid build the following command:
`/usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='NextcloudClient' --net='bridge' -e TZ="America/Los_Angeles" -e HOST_OS="Unraid" -e 'NC_USER'='marc' -e 'NC_PASS'='password' -e 'NC_URL'='https://my.nextcloud.domain/' -v '/mnt/user/music/Explicit/':'/media/nextcloud/':'rw' 'juanitomint/nextcloud-client' `

I tested it with the deeplink to the API as well (as you did not explain which server url is needed):
`/usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='NextcloudClient' --net='bridge' -e TZ="America/Los_Angeles" -e HOST_OS="Unraid" -e 'NC_USER'='marc' -e 'NC_PASS'='password' -e 'NC_URL'='https://my.nextcloud.domain//remote.php/webdav/' -v '/mnt/user/music/Explicit/':'/media/nextcloud/':'rw' 'juanitomint/nextcloud-client' `

After the container starts I found sync db files in the dir:
![2020-06-20 14_27_12](https://user-images.githubusercontent.com/10757176/85201894-09dd6700-b303-11ea-8731-d861c1007999.png)

But my router upload monitor does not show any traffic so its not uploading to my nextcloud.

I can ping my cloud through the NextcloudClient Shell, so it shouldn't be a network issue:
![2020-06-20 14_35_14](https://user-images.githubusercontent.com/10757176/85201967-82442800-b303-11ea-8e11-1001af66bc10.png)

**Comment by mgutt** [comment]
Ok, NC_url must be the full URL to the API as mentioned here:
https://docs.nextcloud.com/desktop/2.5/advancedusage.html#nextcloud-command-line-client

> https://carla:secret@server/nextcloud/remote.php/webdav/

**Comment by mgutt** [comment]
Ok, it seems I did not wait long enough ^^

I played with some variables and this is now the final command generated through Unraid:
```
/usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='nextcloudmusic' --net='bridge' -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -e 'NC_USER'='marc' -e 'NC_PASS'='password' -e 'NC_URL'='https://my.nextcloud.domain/remote.php/webdav/Musik' -v '/mnt/user/music':'/media/nextcloud':'rw' --rm 'juanitomint/nextcloud-client' 
```

As you can see I forgot to set my german timezone in the unraid settings before and I changed the server url so it syncs the local music folder with the target music folder.

I did not set the flags "-it". I do not really understand why they should be needed as we do not pass any shell commands to the docker container?!

P.S. It would be nice if you could add this link to the documentation as it explains the variables like the server url or you add similar explanations:
https://docs.nextcloud.com/desktop/2.6/advancedusage.html#nextcloud-command-line-client

For example this command explained the usage to sync a target folder:
```
$ nextcloudcmd --httpproxy http://192.168.178.1:8080 \
              $HOME/media/music \
              https://server/nextcloud/remote.php/webdav/Music
```

**Comment by juanitomint** [comment]
Would add the link and reference to the README.md
