### ISSUE TITLE
Why is it re-downloading everything?

### ISSUE THREAD

**Issue by mgutt** [juanitomint/nextcloud-client-docker#3]
I wondered why the process took so long so I used `top` to check the pid of my docker container and then this command to check which files are downloaded:

```
lsof -n -p 10484
```

Side question: Is there a better way to check which files are transfered at the moment?

Then I stopped the docker container and checked the local folder. As you can see it generated the temporary *.mp3~xxxxx files and this means it was downloading them until I kicked the container:

![2020-06-21 13_06_16](https://user-images.githubusercontent.com/10757176/85223031-09ef6c80-b3c0-11ea-9bba-c6aff422d30a.png)

EDIT: Ok found the problem. My past syncs were all done through Synology's Cloud Sync and it seems it did not write the correct timestamps. This means all my nextcloud files have the wrong timestamps and need to be re-uploaded first :(

![2020-06-21 13_08_16](https://user-images.githubusercontent.com/10757176/85223095-710d2100-b3c0-11ea-8274-5d02ee6a6f35.png)

But now I first need to restore my local backup 😱

**Comment by juanitomint** [comment]
Good and bad to hear that!
I never experience that in the implementations I made
